### ISSUE TITLE
Any chance to use this with prettier?

### ISSUE THREAD

**Issue by PaulRBerg** [hudochenkov/stylelint-order#100]
I know I can run this plugin via the stylelint CLI, but integrating it with prettier would be pretty cool. I'm referring to prettier's auto-save feature in vscode, where I can tap "CMD+S" and the code gets magically refactored.

**Comment by hudochenkov** [comment]
That would be nice, but this plugin is not concerned to where it could be integrated. I think there would be a technical limitation from VSCode, because it's only possible to have one formatter for a language, so it wouldn't be possible run Prettier and Stylelint with fix at the same time.

**Comment by PaulRBerg** [comment]
I see. I've also just read this issue in prettier's repo: https://github.com/prettier/prettier/issues/1963

It seems they chose not to enforce any kind of css ordering.

**Comment by SharakPL** [comment]
It did work in VSCode, but [last prettier update broke it](https://github.com/prettier/prettier/issues/7090)

**Comment by hudochenkov** [comment]
I'm closing this, because there is nothing could be done in this plugin to achieve what is requested.
