### ISSUE TITLE
Order mixin in sass

### ISSUE THREAD

**Issue by sirion1987** [hudochenkov/stylelint-order#102]
Hello everybody!

I have this sass:

```sass
.heading
  color: $white-color
  +font-size(30)
```
I want to order `+font-size` at the top. I try with this rule:

```json
  "rules": {
    "order/order": [
      [
        {
          "type": "rule",
          "selector": "^\\+[\\w-]+"
        },
        "declarations"
      ]
    ],
```

but I don't get any error message from stylelint.

Can anyone help me? Thank you so much.

**Comment by hudochenkov** [comment]
Please, create a repository with this example and configuration. I'll try to help.

**Comment by sirion1987** [comment]
> Please, create a repository with this example and configuration. I'll try to help.

https://github.com/sirion1987/bemo-example. You can run lint with `yarn lint:sass`. In this case, the linter parses only `hero.sass`. I would like to show an error for line 16. I want `+vertical-padding` before `display`.

Thank you so much.

**Comment by hudochenkov** [comment]
Problem in [postcss-sass](https://github.com/AleshaOleg/postcss-sass) parser, which stylelint uses to parse .sass files. For some reason parser ignore mixins `+something`. So stylelint (and all other plugins) doesn't know anything about this types of mixins. I would suggest open an issue in parser repository or use `@include`.
