### ISSUE TITLE
Unknown rule order error with using ':root' selector

### ISSUE THREAD

**Issue by PaulineNemchak** [hudochenkov/stylelint-order#109]
Hello there, I have an error using :root selector, even in case I delete all other code.
```
src/css/styles.scss
 1:1  ✖  Unknown rule order/order             order/order           
 1:1  ✖  Unknown rule order/properties-order  order/
```

My [.stylelintrc](https://gist.github.com/PaulineNemchak/2e493c3cbddfe06ed3049f0c70765830).

I don't understand why this problem occurs.

**Comment by hudochenkov** [comment]
You need to add `stylelint-order` to `plugins` section of your config (you don't have any):

```js
{
	"plugins": [
		"stylelint-order"
	],
	"rules": {
		// ...
	}
}
```

**Comment by PaulineNemchak** [comment]
thanks a lot, seems missed it

**Comment by hudochenkov** [comment]
Do you have a suggestion how to make it more clear in a readme? It would help new users.
