### ISSUE TITLE
Ordering pseudo elements and pseudo classes?

### ISSUE THREAD

**Issue by JacobDB** [hudochenkov/stylelint-order#114]
I can't seem to find any information about requiring a certain position for pseudo elements (e.g. `::before`) or pseudo classes (e.g. `:first-child`), Is this something that is possible? I'm trying to set up rules to match a format similar to [this blog post](https://www.viget.com/articles/organizing-nested-selectors-in-sass/).

**Comment by hudochenkov** [comment]
I think it's possible. Here some examples:

```js
'order/order': [
	'dollar-variables',
	'at-rules',
	'declarations',
	{
		type: 'at-rule',
		name: 'keyframes',
	},
	{
		type: 'at-rule',
		name: 'media',
	},
	{
		type: 'rule',
		selector: '^&:(hover|focus|active)$',
	},
	{
		// 'BEM modifiers, e. g. &--wide',
		type: 'rule',
		selector: '^&--[\\w-]+$',
	},
	{
		// 'E. g. &.is-open',
		type: 'rule',
		selector: '^&\\.[\\w-]+$',
	},
	{
		// 'E. g. &[disabled]',
		type: 'rule',
		selector: '^&\\[.+\\]$',
	},
	{
		type: 'rule',
		selector: '^&::(before|after)$',
	},
	{
		// 'Pseudo-elements',
		type: 'rule',
		selector: '^&::\\w+$',
	},
	{
		// E. g. @include font-size(16px); Or @include font-size;
		type: 'at-rule',
		name: 'include',
		parameter: 'font-size',
	}
	'rules',
],
```

**Comment by JacobDB** [comment]
Ohh! I must've completely missed the part in the docs that shows how to do regular expressions for rules! Thanks, I think this will get me on the right path!

**Comment by theKashey** [comment]
That is perfect. Literally the last missing piece in the whole picture.
