### ISSUE TITLE
Does this plugin work with styled-component?

### ISSUE THREAD

**Issue by zRelux** [hudochenkov/stylelint-order#116]
I was wondering if this plugin works with styled components.
If so if I could get a basic setup to try it out

**Comment by hudochenkov** [comment]
It does. There are some limitation to autofixing (some times [it won't work](https://github.com/hudochenkov/stylelint-order#autofixing) to avoid breaking styles).

For basic setup you could try my config. Copy content of [this file](https://github.com/hudochenkov/stylelint-config-hudochenkov/blob/29cb804d26c97a715e42ea4d1e21090d61f7a3dc/order.js) to `.stylelintrc.js` in the root of your projects.

Install stylelint and plugin:

```
npm install --save-dev stylelint stylelint-order
```

And run stylelint:

```
stylelint "src/**/*.js"
```
