### ISSUE TITLE
declaration-block-order: Improve warning messages

### ISSUE THREAD

**Issue by hudochenkov** [hudochenkov/stylelint-order#12]
[Current implementation](https://github.com/hudochenkov/stylelint-order/blob/37e6912de2d58c0ecd087df1bba8a64949871e7b/rules/declaration-block-order/index.js#L253):

Message: `Expected ${first} to come before ${second}`.

Possible variations:

Matched pattern | Node description it produce
---|---
custom-properties | `custom property`
dollar-variables | `$-variable`
declarations | `declaration`
at-rule | `at-rule`
at-rule with specified name | `@specified-name`, e. g. `@media`
at-rule with specified name and parameter | `@specified-name parameter`, e. g. `@include /^media/`
at-rule (name, parameter could be specified) with a block | specified text above + " with a block", e. g. `@include /^media/ with a block`
at-rule (name, parameter could be specified) without a block | "blockless " + specified text above, e. g. `blockless @include /^media/`
rule | `nested rule`
rule with specified selector | `nested rule with selector matching "/^&::\w+/"`

Warnings could be like:

```
Expected custom property to come before at-rule
Expected declaration to come before @media
Expected @include /^media/ to come before at-rule
Expected nested rule with selector matching "/^&::\w+/" to come before nested rule
```

How to improve messages?

/cc @jeddy3 If you have a spare minute would you mind help me to figure out better messages, please?

**Comment by jeddy3** [comment]
These all look good to me. My only suggestion would be to drop `nested` as the rule is already scoped to declaration blocks (`declaration-block-*`) e.g.

```
Expected rule with selector matching "/^&::\w+/" to come before rule
```

**Comment by hudochenkov** [comment]
Thank you, @jeddy3 :)
