### ISSUE TITLE
Grouping and ordering

### ISSUE THREAD

**Issue by OddieWallie** [hudochenkov/stylelint-order#120]
Unless there is something we could already use to achieve this...

Would it be possible to alphabetise groups of attributes? For example:

```
.class {
  // Colors
  background-color: black;
  color: white;
  
  // Position
  position: absolute;
  right: 0;
  top: 0;

  // Structure
  height: 20px;
  width: 20px;
}
```
We usually add a comment, to specify the grouping of our attributes. It would be nice if we could enforce ordering groups alphabetically as well.

I imagine we'd need to identify which comments reset the order, seeming as:
```
.class {
   // Group -> resets the order
  margin: 20px;
  padding: 20px 0; // Normal comment -> also accidentally resets ordering
  bottom: 0;
}
```
Might be worth enabling devs to specify this key through REGEX? Something like `// Group: name` would work for us (but probably not for everyone).

**Comment by hudochenkov** [comment]
If you have config [like this](https://github.com/stormwarning/stylelint-config-recess-order/blob/d810de94252e9d7bd50fca175e11b814f29a384d/index.js), you can order everything manually one time to your liking.

**Comment by OddieWallie** [comment]
Even better! Hadn't even thought about fixing it like that. Thanks!
