### ISSUE TITLE
Cannot autofixing css-in-js template literal.

### ISSUE THREAD

**Issue by ramram1048** [hudochenkov/stylelint-order#136]
Cannot autofixing css-in-js template literal.
I just tested `styled-components` only but `Emotion` may can have same issue.
Reproduce code below:

### package.json
```json
"devDependencies": {
  "styled-components": "^5.2.1",
  "stylelint": "^13.10.0",
  "stylelint-order": "^4.1.0"
},
"stylelint": {
  "plugins": [
    "stylelint-order"
  ],
  "rules": {
    "order/properties-order": [
      "width",
      "height"
    ]
  }
}
```

### Component.jsx
```jsx
const haha = /* any styles or functions whatever */;
const Component = styled.a`
  height: 16px;
  width: 16px;
  ${haha}
`;
```
or
```jsx
const haha = /* any styles or functions whatever */;
const Component = styled.a`
  ${haha}
  height: 16px;
  ${haha} /* anywhere */
  width: 16px;
`;
```

Running `npx stylelint "*.jsx" --syntax=css-in-js --fix` shows proper error, but the error doesn't fixed.

**Comment by hudochenkov** [comment]
From readme:

> CSS-in-JS styles with template interpolation [could be ignored by autofixing](https://github.com/hudochenkov/postcss-sorting#css-in-js) to avoid style corruption.

It is impossible to auto fix order, when it has interpolation, and be sure that resulting CSS won't break. E. g. long hand property will be before shorthand.
