### ISSUE TITLE
Per rule configuration

### ISSUE THREAD

**Issue by theKashey** [hudochenkov/stylelint-order#139]
Hey, it might sound a little strange, but I am thinking about different order settings _per file name_, as well as _per rule_.

Technically speaking that's probably stylelint level feature (combing rules), but I would like to start a conversation here, as it can be resolved here as well, but exposing [checkNodeForOrder](https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-order/checkNodeForOrder.js) among the public API.

## Why

The idea is to use something like rational-order, which different _rationales_ for different use cases - in term of BEM - use different styles for `Block`(a rule name matching some pattern) and `Element`(everything else)

Not about allowing/disallowing properties (however, that can be a good idea), but just grouping them in a different order to highlight the difference a little.

**Comment by hudochenkov** [comment]
_Per file_ config could be achieved with `overrides` option, but someone [needs to develop](https://github.com/stylelint/stylelint/issues/3128) it first.

I could understand why _per rule_ config might be needed for BEM. It seems quite specific and unique problem. Theoretically it could be achieved if new stylelint plugin would call this plugin per rule via [`stylelint.utils.checkAgainstRule`](https://stylelint.io/developer-guide/plugins#stylelintutilscheckagainstrule). But currently this utility is limited to stylelint core rules only.

**Comment by hudochenkov** [comment]
Closing as `overrides` are supported in Stylelint now.
