### ISSUE TITLE
`emptyLineBefore` for all groups at once

### ISSUE THREAD

**Issue by robsonsobral** [hudochenkov/stylelint-order#147]
Hi! Thank you so much for help me keep tings organized!

Is there a way to enable `emptyLineBefore` for all groups? I'm using [recess](https://github.com/stormwarning/stylelint-config-recess-order), which has many groups, but no line among them.

Thank you so much!

**Comment by hudochenkov** [comment]
There is not such functionality in `stylelint-order`. However, you could do it yourself with JavaScript. Since stylelint config could be a JavaScript file, you could modify recess config. Get configuration for properties order rule and add `emptyLineBefore` to each properties group:

```js
// .stylelintrc.js
const recessConfig = require('stylelint-config-recess-order');

const recessConfigWithEmptyLine = recessConfig.rules['order/properties-order'].map((group) => {
	return {
		...group,
		emptyLineBefore: 'always',
	}
});

module.exports = {
	extends: ['stylelint-config-recess-order'],
	rules: {
		'order/properties-order': recessConfigWithEmptyLine,
		// your other rules
	}
};
```
