### ISSUE TITLE
Is it possible to change severity of properties-order rule without new primary option values  to use default order ?

### ISSUE THREAD

**Issue by sumegha26** [hudochenkov/stylelint-order#154]
@hudochenkov, 

`"order/properties-order": [ [],
      {
        "severity": "warning"
      }
    ]`

I wanted to change severity of `order/properties-order` as warning. With that don't wanted to specify any custom order but want to use default properties order. (not alphabetical).

Expected -

When I specify primary option as Empty array/undefined in properties - [],  Default order should be used

Is there any other way to change severity of properties order rule, using default properties order ?

**Comment by hudochenkov** [comment]
There is no default order. Plugin doesn't do anything unless order is specified by user. What do you mean by “default order”?

**Comment by sumegha26** [comment]
Okay, understood I will have to specify order.

Default order - I am using nx-stylelint which `extends` config `stylelint-config-idiomatic-order` in `stylelintrc.json`. I am looking for 
1. default properties order used here so that I can specify order config in primary option and `severity` in secondary option or 
2. a way to change `severity` without specifying the order
