### ISSUE TITLE
Exclude `rotate`, `scale` and `translate` from the alphabetical order rule

### ISSUE THREAD

**Issue by jpzwarte** [hudochenkov/stylelint-order#159]
See https://twitter.com/stefanjudis/status/1541365726266662912

Currently behaviour is that it wants to sort these properties alphabetically, but that changes the output.

So this is incorrect atm, but it shouldn't be:

```css
  translate: 50%;
  scale: 1.4;
```

`Expected scale to come before translate (order/properties-alphabetical-order)`

**Comment by hudochenkov** [comment]
Indeed seems like an issue that needs to be fixed. Thank you for bringing an attention.

I never personally supported alphabetical order, so I'm not going to fix this. But if there is a pull request with the fix, I would be more than happy to accept it.

I wonder what would be acceptable automatic sorting for this use case.

- Group these properties and place them after all properties?
- What if there is no order issue (e. g. there is only only of these properties in the rule)? Is property still placed at the end or in correct “alphabetical” order?

**Comment by jpzwarte** [comment]
Apparently I misunderstood and it doesn't matter: https://twitter.com/bramus/status/1541788791677009922

**Comment by hudochenkov** [comment]
I fell in the same trap :) I guess understanding how individual properties work in comparison to `transform` would leave many people puzzled.
