### ISSUE TITLE
Invalid Option error for declaration-block-order

### ISSUE THREAD

**Issue by stormwarning** [hudochenkov/stylelint-order#16]
I'm getting the following error message from Stylelint:
```
Invalid Option:
Invalid option "["custom-properties","dollar-variables",{"type":"at-rule","name":"extend"},{"type":"at-rule","name":"include","hasBlock":false},"declarations",{"type":"at-rule","
hasBlock":true},{"type":"rule","selector":"/^&:[\\w-]+$/"},{"type":"rule","selector":"/^&::[\\w-]+$/"},"rules"]" 
for rule order/declaration-block-order
```

In my `.stylelintrc` I have the following: 
```
"order\/declaration-block-order": [
      "custom-properties",
      "dollar-variables",
      {
        "type": "at-rule",
        "name": "extend"
      },
      {
        "type": "at-rule",
        "name": "include",
        "hasBlock": false
      },
      "declarations",
      {
        "type": "at-rule",
        "hasBlock": true
      },
      {
        "type": "rule",
        "selector": "\/^&:[\\w-]+$\/"
      },
      {
        "type": "rule",
        "selector": "\/^&::[\\w-]+$\/"
      },
      "rules"
    ],
```

Removing the two rule objects clears up the error. Am I escaping the regex incorrectly or something?

**Comment by hudochenkov** [comment]
You don't need `\/` at the start and at the end in JSON:

```json
{
  "type": "rule",
  "selector": "^&:[\\w-]+$"
},
{
  "type": "rule",
  "selector": "^&::[\\w-]+$"
}
```

**Comment by stormwarning** [comment]
Unfortunately, I still get the same error message. Even removing the regex altogether and just using a plain string for the `selector` gives me the same error:
```
      {
        "type": "rule",
        "selector": "div"
      },
      {
        "type": "rule",
        "selector": "span"
      }
```

**Comment by hudochenkov** [comment]
What version do you use? You should be using `0.3.0`.

BTW, in `.stylelintrc` above you have `"order\/declaration-block-order"` while it should be `"order/declaration-block-order"`.

**Comment by stormwarning** [comment]
I thought it might have something to do with a [Stylelint config](https://github.com/stormwarning/stylelint-config-recess-order) my config extends—which used the stylelint-order plugin but was a version behind—but updating that package to use the latest stylelint-order version doesn't seem to have fixed anything.

**Comment by hudochenkov** [comment]
Can you check the version, please? Run `npm list | grep "stylelint-order"` if you on mac or linux.

Also can you share your full `.stylelintrc`?

**Comment by stormwarning** [comment]
Sure thing; it's pretty verbose so I put it up in a gist: https://gist.github.com/stormwarning/7ff3d7a6d6bddfcdb66bff718beae913

`├── stylelint-order@0.3.0`

**Comment by hudochenkov** [comment]
I have no idea what's wrong :( Because configuration is correct and your stylelintrc works great. Can you try to delete node_modules and reinstall everything again?

**Comment by stormwarning** [comment]
It must have had something to do with the project I was on—I tried the config on a more recent project and didn't have any errors. Wiping out `node_modules` and re-installing seemed to do it. Looks like my editor plugin was using an out of date version of Stylelint which was also throwing me off.

Appreciate the help looking into the issue!
