### ISSUE TITLE
`properties-order: null` causes: Unknown severity: "ignore"

### ISSUE THREAD

**Issue by snebjorn** [hudochenkov/stylelint-order#164]
Turning properties-order off by setting it to null 

```json
"rules": {
  "order/properties-order": null
}
```

causes this error to be thrown when something is not sorted correctly.

```
Error: Unknown severity: "ignore"
    at ~\myproject\node_modules\stylelint\lib\formatters\stringFormatter.js:288:12
    at Array.reduce (<anonymous>)
    at stringFormatter (~\myproject\node_modules\stylelint\lib\formatters\stringFormatter.js:258:19)
    at Object.apply (~\myproject\node_modules\import-lazy\index.js:16:20)
    at prepareReturnValue (~\myproject\node_modules\stylelint\lib\prepareReturnValue.js:52:23)
    at standalone (~\myproject\node_modules\stylelint\lib\standalone.js:271:17)
```

A workaround is to
```json
"rules": {
  "order/properties-order": [[], { "severity": "warning" }]
}
```

Also see
- https://github.com/constverum/stylelint-config-rational-order/issues/16
- https://github.com/constverum/stylelint-config-rational-order/issues/13#issuecomment-522421878

`order` doesn't seem to have this issue.
```json
"rules": {
  "order/order": null
}
```

It's common practice in stylelint to set something to null to disable it.
Please fix this error for when `order/properties-order` is set to `null`

**Comment by hudochenkov** [comment]
Could you make a repository with reproducible issue?

**Comment by snebjorn** [comment]
I'll cook something up :)
Gimmi a few days

**Comment by maxming2333** [comment]
I also encountered this problem, `order/properties-order` using `null` to disable is invalid, css file still prompts `order/properties-order` error

```json
"rules": {
  "order/properties-order": null
}
```

Please ask the maintainer to fix this issue

**Comment by snebjorn** [comment]
I was able to reproduce the error in a minimal setup. See setup in the [playground](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AzCEAEwA6A7DGAVgK4DOALgJYoCeAtJLuTE-BqQA4CGYMdARjHIB3GCwDceAlwA2lAOa4GEJi3JteqgE6TcAXzwgANCBSUZMAHJcAtnEQwAHrY4WkYUqWPgVZ+QhAcfAxsEFdieUpcUlC2AG1QihoLOSY6CC1YLVCjEJAklKjyZVw-Oi0uKhVZdMyYLQB6cMjcUIBdIyk8rWILGIQsPGxyYdCMrKatCA56qhhSWqzYjFxemU7gglDmqIaKqtwa8frl8h6YIfIDfW9GPwAxDJtKgMJSFW9YDi9EIK2wiAUDwLUjA5ahAAsSAADEgAGw5LqJcjJGCpYqgzzgkBQgCsMMRwWRqPRixOA1CcJhSAAzIT-gU0UUSmV9pRqjIydkKSBYQBGJAAJlCeD0ID0QA)

It was indeed caused by `stylelint-config-rational-order`
