### ISSUE TITLE
Nested properties

### ISSUE THREAD

**Issue by npoliquin** [hudochenkov/stylelint-order#166]
It is possible to re-order nested properties?

```
font: {
  size: 16px;
  weight: 700;
}

position: absolute;
```

**Expected**
```
position: absolute;

font: {
  size: 16px;
  weight: 700;
}
```

**Comment by hudochenkov** [comment]
It is not possible in this plugin. And will never will. Nested properties are only a Sass feature, and very rarely used, so it doesn't make sense to make codebase complication for it.
