### ISSUE TITLE
Define a skeleton for what is defined inside a selector

### ISSUE THREAD

**Issue by Scipionh** [hudochenkov/stylelint-order#169]
I would like to force the content of my selector to always follow the following skeleton;

1) Properties
2) Pseudo classes
3) Pseudo elements
4) Class/id/attribute modifiers (by instance `&.is-error`, ...)
5) Sibling selectors
6) Descendant selectors

I don't think there is a way to implement that yet with this plugin. Is that something that could be considered ?

**Comment by hudochenkov** [comment]
You may try to achieve this with [extended rule objects](https://github.com/hudochenkov/stylelint-order/tree/master/rules/order#extended-rule-objects). You'll have to write a lot of RegEx.
