### ISSUE TITLE
smacss order

### ISSUE THREAD

**Issue by BarryThePenguin** [hudochenkov/stylelint-order#18]
Would you consider including a `declaration-block-properties-smacss-order` rule?

Similar request to cahamilton/stylelint-config-property-sort-order-smacss#1

I could put together a PR using https://github.com/cahamilton/css-property-sort-order-smacss

cc @cahamilton

**Comment by hudochenkov** [comment]
There is no need for `declaration-block-properties-smacss-order` because it's just a config. I suggest migrate `cahamilton/stylelint-config-property-sort-order-smacss` to `stylelint-order`.
