### ISSUE TITLE
6.0.4 and Stylelint 16: `Unknown rule csstools/use-logical` 

### ISSUE THREAD

**Issue by ai** [hudochenkov/stylelint-order#188]
After updating to Stylelint 16 and `stylelint-order`  6.0.4 I have an error:

```
$ npx stylelint
CommonJS plugins are deprecated ("/home/ai/Dev/slowreader/node_modules/.pnpm/stylelint-use-logical@2.1.0_stylelint@16.0.1/node_modules/stylelint-use-logical/index.cjs"). See https://stylelint.io/migration-guide/to-16
Unknown rule csstools/use-logical  csstools/use-logical
```

Seems like we need something more than https://github.com/hudochenkov/stylelint-order/compare/9a7b56201a5af753557baeb4265650377603ee77...e00347f0facdbe8638c69780fa6d47163fc29f83

**Comment by hudochenkov** [comment]
1. Wrong repository :)
2. I think it should be opened in the [Stylelint repo](https://github.com/stylelint/stylelint). It seems strange that users receive deprecation messages nothing they could do about. As this message is toward plugin developers.

I will switch to ESM, but it would require time, which I don't have at the moment.

**Comment by ai** [comment]
Oh, sorry. Yes, my fault 😅
