### ISSUE TITLE
Update commonjs to esm

### ISSUE THREAD

**Issue by grofzer0** [hudochenkov/stylelint-order#192]
Hello,

Could you update commonjs modules to esm? The commonjs became deprecated in stylelint v16: https://stylelint.io/migration-guide/to-16/#deprecated-commonjs-api

Thanks,
grofzer0

**Comment by hudochenkov** [comment]
Yes, indeed. It should be done preferable before Stylelint 17 release.

**Comment by hudochenkov** [comment]
Done in https://github.com/hudochenkov/stylelint-order/commit/3a6ece9e8fb346442b2d67237bc1854e9619c058. Will be released in the next major version.
