### ISSUE TITLE
Add "unspecified-properties-position" rule

### ISSUE THREAD

**Issue by TrevorSayre** [hudochenkov/stylelint-order#27]
https://github.com/hudochenkov/postcss-sorting/blob/master/docs/unspecified-properties-position.md

`unspecified-properties-position`
`string: "top"|"bottom"|"bottomAlphabetical"`

**Comment by hudochenkov** [comment]
It's here https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-order/README.md#unspecified-topbottombottomalphabeticalignore

**Comment by TrevorSayre** [comment]
Ah, it wasn't listed in the root README. Thank you for pointing me in the right direction.

**Comment by hudochenkov** [comment]
@TrevorSayre No worries. I should make readmes more discoverable.
