### ISSUE TITLE
Request: improve properties-order expect message

### ISSUE THREAD

**Issue by abierbaum** [hudochenkov/stylelint-order#28]
When looking at an error message about property orders it would be nice if the message about  `Expected "a" to come before "b"` would tell you the first (ie. highest) property in the block that "a" needs to come before instead of just telling you the one that is currently above it.

For example in the css below, the z-index needs to come first.  But the message says `Expected "z-index" to come before "height"`.  If it could say instead `Expected "z-index" to come before "position"` it would help users to immediately know where they can move it to pass that lint error.   Instead I end up having to copy it up one, then up another, then up another, and so on. Basically performing a manual cut/paste bubblesort.  Seems like this could be improved.

note: in this example I will end up having to bubble up several of the items so it kind of shows a worst case.

```css
my-cmp {
   position: fixed;
   padding: 0;
   top:     0;
   height:  100%;
   z-index: 100;
}
```

**Comment by hudochenkov** [comment]
I'll think about it.

In the mean time, you don't have to manual sort! There is fantastic tool to automate this — [postcss-sorting](https://github.com/hudochenkov/postcss-sorting).

**Comment by abierbaum** [comment]
@hudochenkov That tool looks great.  Especially interested in the vscode plugin.  I can't find a way to share configuration though.  So for example if I have my stylelint.config.js file build up a set of ordering rules I would like to share them over to postcss-sorting (and into the vscode plugin) so I don't have to duplicate them.  I don't see a way to do this right now. :(

**Comment by hudochenkov** [comment]
Currently you have to duplicate config. But [soon](https://github.com/hudochenkov/postcss-sorting/issues/23#issuecomment-303983265) (in a month or two) it wouldn't be necessary. You'll need only one configuration.

**Comment by wojtask9** [comment]
This would be a great improvement for `stylelint-scss` users.
Are there any plans to resolve this issue ?

**Comment by hudochenkov** [comment]
This kind of messages might be helpful if only one property is misplaced. But if there are multiple properties misplaced, there will be the same confusion.

For example, we have following config and CSS:

```json
{
	"rules": {
		"order/properties-order": [
			"margin",
			"padding",
			"width"
		]
	}
}
```

```css
div {
	width: 0;
	padding: 0;
	margin: 0;
}
```

And there are warnings:

```
Expected "margin" to come before "padding"
Expected "padding" to come before "width"
```

You follow first warning and move `margin`:

```css
div {
	width: 0;
	margin: 0;
	padding: 0;
}
```

Then follow second warning and move `padding`:

```css
div {
	padding: 0;
	width: 0;
	margin: 0;
}
```

Boom, you followed warnings but ended up with the wrong order. How does that happen? You should remember all stack of properties that you already moved. I. e. you for the second warning you should remember that `margin` should be before `padding` and move not only `padding` before `width`, but `margin` and `padding`.

As you see there is no point of more precise warnings, as it requires even more mental work to follow and achieve correct order.

The good news is starting `stylelint@7.11.0`, and `stylelint-order@0.5.0` order is auto-fixable using `stylelint --fix`. Don't need to do manual ordering any more.

**Comment by wojtask9** [comment]
Maybe something like this:
if there is only one 'warning' then report
`Expected "margin" to come before "padding"`
otherwise  report full order
`Expected order "margin, padding, width"`

**Comment by jsit** [comment]
Hm, I'd still like to see this as a possibility (a more informative error message) even though there are tools to automatically sort for you.
