### ISSUE TITLE
Allow stylelint fix to make order changes?

### ISSUE THREAD

**Issue by TrevorSayre** [hudochenkov/stylelint-order#30]
Is there a way for the `--fix` option of the stylelint CLI to handle these ordering rules automatically? Or is there a quick way to auto-fix css based on these ordering rules via some other CLI tool?

Once added, or if a solution exists, please add to README.

**Comment by hudochenkov** [comment]
stylelint doesn't have `--fix` option released yet. Use [postcss-sorting](https://github.com/hudochenkov/postcss-sorting) for automatic sorting. It has almost the same config as stylelint-order.

**Comment by jitendravyas** [comment]
Couldn't automatic sorting can have side effect?

**Comment by hudochenkov** [comment]
It can, of course, but most likely you won't have any. Take a look on [Handling comments](https://github.com/hudochenkov/postcss-sorting#handling-comments) section. It worth to keep in mind. You can try postcss-sorting on your codebase and see if it's working as you want.

**Comment by TrevorSayre** [comment]
Thanks, got this working via https://github.com/postcss/postcss-cli

**Comment by hudochenkov** [comment]
stylelint-order 0.5.0 released! With autofixing!
