### ISSUE TITLE
Feature: CSS order presets

### ISSUE THREAD

**Issue by hotforfeature** [hudochenkov/stylelint-order#31]
I use [Concentric CSS](https://github.com/brandon-rhodes/Concentric-CSS) as the basis for my CSS property ordering. Coming from `sass-lint`, there is a rule for [`property-sort-order`](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/property-sort-order.md) that allows certain style presets such as alphabetical, [concentric](http://rhodesmill.org/brandon/2011/concentric-css/), [recess](http://twitter.github.io/recess/), and [smacss](https://smacss.com/book/formatting).

It would be great if we could have these presets as a configuration option in addition to manually specifying a property order.

**Comment by hudochenkov** [comment]
You can use shareable config https://github.com/chaucerbao/stylelint-config-concentric-order. This config use stylelint-order.

**Comment by hotforfeature** [comment]
That's perfect. Now that I know what to look for I also found

https://github.com/stormwarning/stylelint-config-recess-order
https://github.com/cahamilton/stylelint-config-property-sort-order-smacss

What d'you think about adding a "Presets" or some similar section in the readme that links to these three popular formats?

**Comment by hudochenkov** [comment]
I don't think it's a good idea to have this section. Anyway, thanks for a research :)
