### ISSUE TITLE
Setting `properties-alphabetical-order: false` causes linting loop

### ISSUE THREAD

**Issue by edwinwright** [hudochenkov/stylelint-order#33]
Testing in Atom, using the `linter` and `linter-stylelint` packages.
If you set `properties-alphabetical-order: false`, the linter treats it as true and runs this linting rule.
Expect that the rule is not run.

**Comment by jeddy3** [comment]
[Use `null`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#how-do-i-disable-a-rule) e.g. `"properties-alphabetical-order": null`.

**Comment by edwinwright** [comment]
Thanks. Any plans to get this working with `false`?

**Comment by hudochenkov** [comment]
> Any plans to get this working with `false`?

I don't [think](https://github.com/stylelint/stylelint/issues/2611) so.
