### ISSUE TITLE
Descending specificity error with different classes.

### ISSUE THREAD

**Issue by fleeting** [hudochenkov/stylelint-order#34]
I'm getting `Expected selector ".super-navigation ul a" to come before selector ".navigation ul a:hover"` with the following CSS:

```
.navigation ul {
  margin: 0;

  a {
    color: #fff;

    &:hover {
      color: #eee;
    }
  }
}

.super-navigation ul {
  margin: 0;
  padding: 0;

  a {
    color: #fff;

    &:hover {
      color: #eee;
    }
  }
}
```

**Comment by hudochenkov** [comment]
Wrong repository. Looks like it's a core stylelint rule.

**Comment by jeddy3** [comment]
@fleeting FYI, this is being tracked in the stylelint issue tracker - https://github.com/stylelint/stylelint/issues/2489. The issue is labelled as `help wanted` and `beginner friendly`, so please consider contributing a fix if you'd like to see this issue resolved.
