### ISSUE TITLE
[Feature request] List unparsed properties

### ISSUE THREAD

**Issue by meduzen** [hudochenkov/stylelint-order#38]
I would find nice if _styleint-order_ could list the declarations of a stylesheet (SCSS) that are not parsed by this plugin. This would help to better spot potentially unwanted declarations and to better iterate on the list of `order/order` declarations while CSS evolve in time.

A property like `listUnparsed` would be great. What do you think? Is there any chance this could be a thing?

Thanks for contributor’s job on this plugin.

**Comment by hudochenkov** [comment]
Sorry, I don't see this feature in the scope of this plugin. Most likely only a few people would need such functionality.
