### ISSUE TITLE
Disable properties-alphabetical-order rule

### ISSUE THREAD

**Issue by tirli** [hudochenkov/stylelint-order#42]
Hi.
I'm using [stylelint-config-concentric-order](https://github.com/chaucerbao/stylelint-config-concentric-order) based on your package. But then I'm getting an error both from properties-order and alphabetical-order rules. 
I've tried to write `"order/properties-alphabetical-order": false` in a config, but seems like it doesn't disable the rule. Am I doing something wrong?

**Comment by hudochenkov** [comment]
Could you provide your full stylelint config? What's your stylelint and stylelint-order versions? What errors do you get?

To [disable a rule](https://stylelint.io/user-guide/faq/#how-do-i-turn-off-disable-or-ignore-a-rule) use `null`:

```js
"order/properties-alphabetical-order": null
```

**Comment by tirli** [comment]
@hudochenkov Thanks. Using `null` helps me. Sorry for disturbing. Also, I think that this issue should be created in [stylelint-config-concentric-order](https://github.com/chaucerbao/stylelint-config-concentric-order) package, not in yours

**Comment by hudochenkov** [comment]
No worries.

I don't see a problem with `stylelint-config-concentric-order`. They don't enable `order/properties-alphabetical-order` rule.

**Comment by tirli** [comment]
@hudochenkov 
Hmm...I'm not enabling it too. Here is my stylelintrc
``` json
{
  "extends": [
    "stylelint-config-sass-guidelines",
    "stylelint-config-concentric-order"
  ],
  "plugins": [
    "stylelint-scss"
  ],
  "rules": {
    "order/properties-alphabetical-order": null
  }
}
```
And there are errors if I remove ` "order/properties-alphabetical-order": null`.
I'm using such versions:

```
    "stylelint": "^8.0.0",
    "stylelint-config-concentric-order": "^2.1.2",
    "stylelint-config-sass-guidelines": "^3.1.0",
    "stylelint-scss": "^2.0.1"
```

**Comment by hudochenkov** [comment]
The guilty is [found](https://github.com/bjankord/stylelint-config-sass-guidelines/blob/81323826dffaaa6b39c522d4698f21f365903a1c/index.js#L39) :)

**Comment by luckysinghkathaith** [comment]
body{background-color:#EAF6F6;}
hr{border-style:none;
  border-top-style:dotted;
  border-color: grey;
  border-width: 5px;
  width:5%;}

pls help me , it showing a error that rule doesn't have all its properties in alphabetical order

**Comment by Vihaan-Singhal** [comment]
I am facing the same problem
