### ISSUE TITLE
[properties-alphabetical-order] Prefixed properties doesn't precede the unprefixed version

### ISSUE THREAD

**Issue by cmalard** [hudochenkov/stylelint-order#44]
**"stylelint-order": "^0.6.0"**

Hello there,
```diff
-  -moz-osx-font-smoothing: grayscale !important;
-  -ms-overflow-style: scrollbar;
-  -webkit-font-smoothing: antialiased !important;
  background-color: $content-bg;
  color: $font-color;
  font-family: $font-roboto;
  font-size: $font-size-base;
+  -moz-osx-font-smoothing: grayscale !important;
+  -webkit-font-smoothing: antialiased !important;
  font-weight: $font-weight-normal;
+  -ms-overflow-style: scrollbar;
  padding-top: 75px;
  text-rendering: optimizeLegibility !important;

```
It should be the contrary, any idea why it's happening ?

`.stylelintrc`
```json
{
  "extends": [
    "stylelint-config-standard"
  ],
  "plugins": [
    "stylelint-order"
  ],
  "rules": {
    "order/properties-alphabetical-order": true
  }
}
```

**Comment by PaulRBerg** [comment]
As per the csslint [wiki](https://github.com/CSSLint/csslint/wiki/Require-standard-property-with-vendor-prefix), sometimes it's recommended to have the standard version of the property after the vendor version, to ensure that it will work nevertheless.

I know that this kind of edge case is hard to handle, but it's kinda important, particularly to those that experiment with new css features.

**Comment by hudochenkov** [comment]
@PaulRBerg this is correct. That's why prefixed properties always sorted before unprefixed properties with the same name.
