### ISSUE TITLE
cant install with stylelint 8.1.1

### ISSUE THREAD

**Issue by ctf0** [hudochenkov/stylelint-order#46]

**Comment by hudochenkov** [comment]
Please explain.

**Comment by ctf0** [comment]
atm i have styline 8.1.1 globally installed but the package require
https://github.com/hudochenkov/stylelint-order/blob/4be7f5dcf3f63e35b5e366c65c71283f514e1a01/package.json#L35

so i cant install it and keep getting error for not finding peerDependencies

**Comment by hudochenkov** [comment]
Where stylelint-order is installed? Where is your stylelint configuration located?

**Comment by ctf0** [comment]
am also trying to install `stylelint-order` globally , the stylelint configuration is at `~/.stylelintrc.json`

**Comment by hudochenkov** [comment]
Then you need to install it in your user directory `~/`.

**Comment by ctf0** [comment]
am kinda lost, shouldn't `npm install stylelint-order -g` suffice ?

**Comment by hudochenkov** [comment]
stylelint will look for plugins starting from config directory and won't look into global packages.

**Comment by ctf0** [comment]
ah okay, i know its not related to u but honestly this is dump, as now the package wont be updateable like any other npm package, and will make the home path even more polluted.

still thanx for ur help.

**Comment by hudochenkov** [comment]
Recommended to have linters (and almost any other Node.js tools) installed on per project basis and not globally.

**Comment by sanmai-NL** [comment]
@hudochenkov This doesn't apply if you use containers.
