### ISSUE TITLE
declaration-block-order: Support Less variables

### ISSUE THREAD

**Issue by PsiXdev** [hudochenkov/stylelint-order#5]
As I wrote in this comment https://github.com/hudochenkov/stylelint-order/pull/3#issuecomment-263495948, it would be nice to support Less variables. We want to describe variables in the beginning of the rules, for example.

```
.class {
	@variable: 10px;
	
	margin: @variable;

	.nested {
		...
	}
}
```

I think that this problem may be solved by adding RegEx patterns to declarations config, but you can simply add a new type, like dollar-variables.

**Comment by hudochenkov** [comment]
Thank you for suggestion! Use new `at-variables` keyword for `declaration-block-order` in `0.3.0`.
