### ISSUE TITLE
introduce fuzzy selector for properties

### ISSUE THREAD

**Issue by ThePeach** [hudochenkov/stylelint-order#52]
I've found the ordering of the properties a bit tedious, I wonder if it's possible to introduce a fuzzy ordering of some sort, e.g.:

    [ "border", "border-*" ]

the following statement won't cause a warning:

    .rule {
      border: 10px solid red;
      border-bottom: 5px;
      border-right-color: green;
    }

where the fuzzy properties are going to be ruled by either `unspecified` or by introducing a specific one like: `fuzzy` that works the same way as `unspecified`.

for instance:

    [
      [ "border*" ],
      { "fuzzy": null }
    ]

that won't cause warning for the following:

    .rule {
      border: 10px solid red;
      border-right-color: green;
      border-bottom: 5px;
    }

hope it makes sense. :smile:

**Comment by hudochenkov** [comment]
There was such functionality, but it was removed in v0.5.0 as it caused ambiguity.

E. g.:

```js
["border", "border-*"]
```

```css
.foo {
    border-bottom-color: yellow;
    border-color: red;
}
```

`border-bottom-color` will be overritten in browser by `border-color`.

I don't have plans to bring it back.
