### ISSUE TITLE
unprefixed property names could support regular

### ISSUE THREAD

**Issue by hangyangws** [hudochenkov/stylelint-order#56]
properties-order array list is too long,

and it not  support regular

**Comment by hudochenkov** [comment]
Sorry, I don't understand what you're asking.

**Comment by hangyangws** [comment]
This is part of the `.stylelinerc` in my project :  

```json
{
  "order/properties-order": [
    "position",
    "top",
    "right",
    "bottom",
    "left",
    "float",
    "clear",
    "display",
    "flex",
    "flex-grow",
    "flex-shrink",
    "flex-basis",
    "flex-flow",
    "flex-direction",
    "flex-wrap",
  ]
}
```

The problem is ：  
If I do not consider the inner order that start with  flex .
The `order/properties-order` array values do not support regular expressions.
Such as given "is not support":

```json
{
  "order/properties-order": [
    "position",
    "top",
    "right",
    "bottom",
    "left",
    "float",
    "clear",
    "display",
    /^flex/,
  ]
}
```

So developers have to Write all CSS listKeys."This behavior is very unwise"

**Comment by hangyangws** [comment]
I am not very good at English expression, please forgive me

**Comment by hudochenkov** [comment]
Thank you for your explanation!

This functionality won't be added. Please, read my explanation in similar issues: https://github.com/hudochenkov/stylelint-order/issues/43, https://github.com/hudochenkov/stylelint-order/issues/52.
