### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by SuperEngineer64** [hudochenkov/stylelint-order#69]
Thanks for your work!

My code is marked red, if the order I configured is wrong. But there is no error message, so I can not know, where the error is coming from while working in the project.

How can I add a message? This isnt working: https://stylelint.io/user-guide/configuration/#custom-messages

Thanks! :)

**Comment by hudochenkov** [comment]
There is always an error message. What is your configuration? How do you use it? Screenshot?

**Comment by SuperEngineer64** [comment]
Hey!

Iam using Sublime with stylelint and stylelint-order. In my project root I have the .stylelint.json file. And in it:

`{  
  "extends": "stylelint-config-recommended",
  "extends": "stylelint-config-standard",

  "plugins": [
    "stylelint-order"
  ],
  
  "rules": {
    "order/order": [
      "custom-properties",
      "declarations"
      
    ],
    "order/properties-order": [
      "color",
      "display",
      "padding",
      "margin"
    ]
  }
}`

**Comment by hudochenkov** [comment]
Check SublimeLinter settings. I use it as well and I see an error message when hover over errored area.

![image](https://user-images.githubusercontent.com/654597/45423204-e77cdb00-b692-11e8-9ef4-6fab7e39327b.png)

![image](https://user-images.githubusercontent.com/654597/45423257-12672f00-b693-11e8-9604-57b1f0f32b98.png)

**Comment by SuperEngineer64** [comment]
Hm.. I only get "Definitions" and "References" on hover.

**Comment by hudochenkov** [comment]
Do you see error messages when there are other violations? For example, you should have see an error message with the following CSS:

```
.a {}
.a {}
```

BTW, there is an problem with your stylelint config:

```
  "extends": "stylelint-config-recommended",
  "extends": "stylelint-config-standard",
```

Should be:

```
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-standard",
  ],
```

**Comment by SuperEngineer64** [comment]
Solution:

Removing all settings after "extend", save, restart, open and past the settings again.
Now its working....

And as I discovered, all stylelint messages were away. No there back again. Thats the kind of bug nobody wants. :p

Thanks!
