### ISSUE TITLE
Migration tips

### ISSUE THREAD

**Issue by in-in** [hudochenkov/stylelint-order#7]
Unfortunately stylelint removed `declaration-block-properties-order` and forces to use stylelint-order. 
But stylelint-order overcomplicated compared with `declaration-block-properties-order` in stylelint. 
Can you provide some example how my stylelint config should looks in  stylelint-order world?
https://gist.github.com/in-in/c261ee397999bec6f8294abd50adfb9d
Thanks.

**Comment by hudochenkov** [comment]
You should install `stylelint-order`:

```
npm install stylelint-order
```

Then add plugin to config (`plugins` section):

```js
{
    "plugins": [
        "stylelint-order"
    ],
    "rules": {
    }
}
```

And configure `order/declaration-block-properties-specified-order` rule:


```js
{
    "plugins": [
        "stylelint-order"
    ],
    "rules": {
        "order/declaration-block-properties-specified-order": [
            "margin",
            "padding"
        ]
    }
}
```

**Comment by in-in** [comment]
It will work with stylefmt?

**Comment by hudochenkov** [comment]
No. You could use [`postcss-sorting`](https://github.com/hudochenkov/postcss-sorting/), but it requires separate setup and config.

**Comment by in-in** [comment]
I checked readme of that tool and I can’t find information about autofix feature

**Comment by hudochenkov** [comment]
There no “autofix”. You should run it like stylefmt, but it has config different than stylelint. Actually stylefmt uses postcss-sorting under the hood.

For your case config for `postcss-sorting` will look like:

```json
{
    "properties-order": [
        "margin",
        "padding"
    ]
}
```

**Comment by in-in** [comment]
But why you recommend that tool?

**Comment by hudochenkov** [comment]
Because I'm the author of both these plugins ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯ `stylelint-order` checks the order, `postcss-sorting` sort stylesheets in required order. Currently you have to use different configuration for them. `stylefmt` doesn't support `stylelint-order`rules, so you have to use `postcss-sorting` if you want to use tools which will check properties order and sort them for you.

**Comment by in-in** [comment]
Ok now I get it
postcss-sorting works with stylefmt, right?

**Comment by hudochenkov** [comment]
Not exactly, stylefmt uses postcss-sorting, but users don't know about it :)

**Comment by pawelgrzybek** [comment]
Hi @hudochenkov .

Very related question. I managed how to get stylelint-orderwworking fine with stylelint config file. I have a small issue when I use global .stylelintrc file that sits on my root directory. How should I specify `configBasedir` to get it work?

Thanks in advance and thanks for amazing plugins mate!

**Comment by hudochenkov** [comment]
@pawelgrzybek I suppose you're using globally installed `stylelint` with global `.stylelintrc`? I believe you don't need to specify `configBasedir`. Just install `stylelint-order` globally: `npm i -g stylelint-order`.

**Comment by pawelgrzybek** [comment]
Yeah, it is correct @hudochenkov, I use globally installed `stylelint` + global `.stylelintrc`.

Your recommendation is what I initially thought. Unfortunately my editor cannot find `stylelint-order` without `configBasedir`. Will try to set that up one more time later on and let you know when I find out a solution.

Thanks again.

**Comment by hudochenkov** [comment]
@pawelgrzybek indeed, I was wrong. You need to install `stylelint-order` in the same directory where your global config is. Just run `npm i stylelint-order`.

**Comment by pawelgrzybek** [comment]
O wow. Thats a bit messy. Don't you think so. My home folder isn't probably the best place to keep `node_modules`. Thanks for advice confirmation mate. There must be a bit better solution for that, I will figure it out and let you know...

**Comment by hudochenkov** [comment]
Yeah, it's messy. This is why it's recommended to have stylelint with its plugins installed for every project like every other dependency.
