### ISSUE TITLE
exposing an error message when extending at-rules

### ISSUE THREAD

**Issue by sturobson** [hudochenkov/stylelint-order#75]
Stylelint (from my brief experience) allows you to create a custom error message, for example:

```js
    "indentation": [ 2, {
        "except": ["block"],
        "message": "Please use 2 spaces for indentation. Tabs make Stuart very grumpy.",
        "severity": "warning"
      } ]
```

I've tried adding `"message"`, and `"severity"` to an extended at-rules in my config but this doesn't bubble up when an error occurs.

My config for stylelint-order is:

```js
"order/order": [
        "custom-properties",
        "dollar-variables",
        {
          type: 'at-rule',
          name: 'include',
          parameter: 'set-*',
          message: 'Make sure your mixins are at the top'
        },
        "declarations",
        "rules",
        {
        	type: 'at-rule',
        	name: 'media',
        	hasBlock: true
        }
      ],
      "order/properties-alphabetical-order": true,
```

Does `"message"` and/or `"severity"` not work this way? 

When running the style lint with above code I get:

```bash
components/containers/vf-content/vf-content.scss
81:5	⚠  Expected @include "set-*" to come before declaration (order/order) [stylelint]
```

Do you think this is something that is possible (with help)?

Thanks in advance, and thanks for creating this plugin for style lint 👍

**Comment by hudochenkov** [comment]
It's it possible to set a custom message as for any other rule. But with stylelint-order it's not that helpful, because it is set to a whole rule:

```
"order/order": [
  [
    "custom-properties",
    "dollar-variables",
    {
      type: 'at-rule',
      name: 'include',
      parameter: 'set-*',
    },
    "declarations",
    "rules",
    {
      type: 'at-rule',
      name: 'media',
      hasBlock: true
    }
  ],
  {
    message: 'Hello',
    severity: 'warning',
  }
],
```

It might be possible to implement in a way you're showing. But it will be tricky and won't make much difference for the majority of users.
