### ISSUE TITLE
Complex sorting rule

### ISSUE THREAD

**Issue by nosovk** [hudochenkov/stylelint-order#81]
Sorting properties in alphabetical order is a good starting point, but better stick to more verbose standard:

1. Layout Properties (position, float, clear, display)
2. Box Model Properties (width, height, margin, padding)
3. Visual Properties (color, background, border, box-shadow)
4. Typography Properties (font-size, font-family, text-align, text-transform)
5. Misc Properties (cursor, overflow, z-index)

Is it possible to declare such an order somehow?

**Comment by hudochenkov** [comment]
Yes. With [`order/properties-order`](https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-order/README.md).

Define your own order or use community configs:

https://www.npmjs.com/package/stylelint-config-recess-order
https://www.npmjs.com/package/stylelint-config-rational-order
https://www.npmjs.com/package/stylelint-config-idiomatic-order
https://www.npmjs.com/package/stylelint-config-property-sort-order-smacss
