### ISSUE TITLE
Autofix not working for styled components

### ISSUE THREAD

**Issue by ekfuhrmann** [hudochenkov/stylelint-order#97]
I didn't want to clutter up #63, but do want to thank you for everything you do with stylelint and for taking the time to send me over your configs.

I got your styled-components stylelint configs working, however I'm unable to get autofix to work. 

In your environment, does autofix on save actually work for ordering styled components? If so, it might be a vscode setting conflict that I'm running into? I've been trying for awhile to get the ordering for styled components to work as well as it does for my SCSS files.

**Comment by hudochenkov** [comment]
I don't have autofix on save, but it's run as precommit hook. For styled components there are exceptions, when autofix skips component. It skips, where it's not safe to change the order: interpolation on the same level as properties.

Interpolation as one of the nodes in the rule, so it's unsafe to autofix:

```js
const A = styled.div`
  color: red;
  ${something}
  display: inline;
`;
```

Interpolation as a value of property — safe to autofix:

```js
const A = styled.div`
  color: ${something};

  display: inline;
`;
```

Interpolation in selector — safe to autofix:

```js
const A = styled.div`
  color: red;
  display: inline;

  ${ComponentB} {
	  display: none;
  }
`;
```

**Comment by ekfuhrmann** [comment]
That makes sense.

I have not messed around much with pre-commits, but I'll take a look into it some more.  Thanks again!

**Comment by Inokcode** [comment]
Anyone know 
"Beware that due to limitations on what is possible for Stylelint custom processors we cannot support the --fix option"
https://styled-components.com/docs/tooling#stylelint

solution for auto fix styled components

**Comment by shooftie** [comment]
@hudochenkov what makes you say that it is "not even possible with vscode-stylelint"?

**Comment by hudochenkov** [comment]
@shooftie it was written 3 years ago. Things might work differently at that time.

**Comment by shooftie** [comment]
I have subsequently been through a great many comments, a loyal of which were written by you. I know now that autofix does work... most of the time!
